version: '3.9'

services:
  api:
    restart: always
    build: 
      context: .
      target: production
    container_name: api
    ports:
      - 5000:5000
    networks:
      - uganda-football-api
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - uganda-football-api
    volumes:
      - mongo-data:/data/db

networks:
  uganda-football-api:
    driver: bridge

volumes:
  mongo-data:
    driver: local